import { Libre_Baskerville, Sahitya } from 'next/font/google';
import './globals.css';

const libreBaskerville = Libre_Baskerville({ 
  weight: ['400'],
  subsets: ['latin'],
   variable: '--font-libre-baskerville' });


const sahitya = Sahitya({
  weight: ['400'],
   subsets: ['latin'],
    variable: '--font-sahitya' });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={`${libreBaskerville.variable} ${sahitya.variable}`}>
        {children}
      </body>
    </html>
  );
}